apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: rapidrar-ingress
  namespace: rapidrar
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/proxy-body-size: "50m" # Allow larger file uploads
spec:
  ingressClassName: nginx
  rules:
  - host: rapidrar.example.com
    http:
      paths:
      - path: /
        pathType: Prefix
        backend:
          service:
            name: rapidrar-svc
            port:
              number: 80
