apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: rapidrar-daemonset
  labels:
    app: rapidrar
spec:
  selector:
    matchLabels:
      app: rapidrar
  template:
    metadata:
      labels:
        app: rapidrar
    spec:
      containers:
      - name: rapidrar
        image: ghcr.io/alittlecrocodile/rapidrar:${GITHUB_SHA}
        imagePullPolicy: IfNotPresent
        command: ["uvicorn"]
        args: ["src.api:app", "--host", "0.0.0.0", "--port", "8000"]
        ports:
        - containerPort: 8000
        resources:
          limits:
            memory: 200Mi
            cpu: 500m
          requests:
            memory: 100Mi
            cpu: 100m
