apiVersion: v1
kind: Service
metadata:
  name: rapidrar-svc
  namespace: rapidrar
spec:
  selector:
    app: rapidrar
  ports:
    - protocol: TCP
      port: 80
      targetPort: 8000
  type: ClusterIP
